[theme]
# Primary accent for interactive elements
primaryColor="#523030"

# Background color for the main content area
backgroundColor="#e8e0e0"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#f1ede7"

# Color used for almost all text
textColor="#1a1515"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
